<%
  String base_dir = request.getContextPath();
%>
<html><head>
<link rel="stylesheet" type="text/css" href="<%=base_dir%>/css/styles.css"/></head>
<body>
<div id="topheader">
<span id="version">Version 0.92.0</span>
<span id="title">BECTA/COL Web Services</span>
</div>
<div id="header">
<ul><li><a href="index">Home</a></li>
<li><a href="general">Intro</a></li>
<li><a href="docs">Docs</a></li>
<li><a href="searches">Test Searches</a></li>
<li><a href="sample">Sample Code</a></li>
<li><a href="soap">Soap</a></li>
<li><a href="troubleshooting">Troubleshooting</a></li>
<li id="current"><b>Housekeeping</b></li>
</ul>
</div>
<div style="clear: both">&nbsp;</div>
<div id="main">
<h1>General housekeeping / sysadmin howto</h1>
<p>
An important feature of the new system is that, with sufficient
techinical knowledge, new search access points (EG, the ability to
search by as yet undefined fields such as platform="WindowsNT") can be
added to the live service without writing any new code, simply through
modification of a few XML configuration files. Similarly, new
attributes can be added to the output XML records, and new profiles can
be supported without writing new code.

<ul>
  <li>Extending search - Adding a new search access point
    <ul>
	<li>Modify iNodeDataDictionary.xml - make sure that there is an entry for the target entity you want to search against. (Example)</li>
	<li>Make sure that there is an access path from the base entity to your target entity (Example)</li>
	<li>Make sure that there is an entry for the field you want to search against (Example)</li>
        <li>Edit iNodeAccessPoints.xml - Add the access point you want to provide, select the correct mapping class, eg, FreeTextMapping, add the access path from the base entity for each collection to the target entity / attribute</li>
        <li>test - restart the backend search process (No need to bouce webapp, no interruption to normal operation) and try to search for your newly defined attribute, check logs for errors, check results are expected, check SQL generated (sent to log also)</li>
    </ul>
  </li>
  <li>Adding attributes to the returned XML result fragments
    <ul>
      <li>Modify iNodeTemplates.xml - Add in the attributes you want displayed.</li>
      <li>Locate the template that transforms database XML records generated by the template into profile specific records, eg, the DBProductToLom.xsl file and add in a select for the new source attribite, with the appropriate wrapping XML for the target profile schema.</li>
    </ul>
  </li>
</ul>
</p>
<p>
After configuring a new search, you see:
</p>
<div class="code">68728   [Thread-3] DEBUG org.jzkit.search.util.ResultSet.SimpleAggregatingResultSet  - Waiting for more records to become available. Current hwm=-1
<br/>
com.microsoft.sqlserver.jdbc.SQLServerException: SELECT permission denied on object 'COL_DERIVED_PRODUCT_DISCIPLINE', database 'COLMSIB_commerce_db', schema 'dbo'.
</div>
<p>
In the search logs. You need to grant select permission on the identified table.
</p>

</div>
</body></html>
